### ISSUE TITLE
Cnn-messaging crashes when trying to process a json payload that is empty

### ISSUE THREAD

**Issue by c-tcsict-mlandry** [cnnlabs/cnn-messaging#8]
It should probably handle it in a more graceful manner. I will try to create a PR if I have the time.

**Comment by niahmiah** [comment]
Thanks for the report. Can you please provide more details about how to reproduce this?

**Comment by rwinbush** [comment]
The happens when there is a bad JSON string in the message.  fromAmqp() uses JSON.parse().  We were getting data that had a property like this in the "event" payload:
"cmsId":875",
close quote but no open quote.  I do not think the producer end of this is using the cnn-messaging module so it is probably an issue with their code. We should probably protect ourselves here though (and maybe even at the application level as well) so that bad data can't bing down the entire app.

**Comment by niahmiah** [comment]
Since this is not an asynchronous method, I think throwing an error is still the appropriate thing to do here. If I was to wrap it with try/catch, what else would I do with the error?

Please reopen if you disagree
